// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// acf_sign_lag_mean_cpp
List acf_sign_lag_mean_cpp(const NumericVector& z_full, const LogicalVector& mask_full, const IntegerVector& dims, const IntegerVector& lag_xyz, const double clip);
RcppExport SEXP _neurothresh_acf_sign_lag_mean_cpp(SEXP z_fullSEXP, SEXP mask_fullSEXP, SEXP dimsSEXP, SEXP lag_xyzSEXP, SEXP clipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type z_full(z_fullSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type mask_full(mask_fullSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type lag_xyz(lag_xyzSEXP);
    Rcpp::traits::input_parameter< const double >::type clip(clipSEXP);
    rcpp_result_gen = Rcpp::wrap(acf_sign_lag_mean_cpp(z_full, mask_full, dims, lag_xyz, clip));
    return rcpp_result_gen;
END_RCPP
}
// bbox_from_indices_cpp
IntegerVector bbox_from_indices_cpp(const IntegerVector& idx, const IntegerVector& x, const IntegerVector& y, const IntegerVector& z);
RcppExport SEXP _neurothresh_bbox_from_indices_cpp(SEXP idxSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(bbox_from_indices_cpp(idx, x, y, z));
    return rcpp_result_gen;
END_RCPP
}
// split_indices_bbox_cpp
List split_indices_bbox_cpp(const IntegerVector& idx_parent, const IntegerVector& child_id, const int m, const IntegerVector& x, const IntegerVector& y, const IntegerVector& z);
RcppExport SEXP _neurothresh_split_indices_bbox_cpp(SEXP idx_parentSEXP, SEXP child_idSEXP, SEXP mSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type idx_parent(idx_parentSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type child_id(child_idSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(split_indices_bbox_cpp(idx_parent, child_id, m, x, y, z));
    return rcpp_result_gen;
END_RCPP
}
// split_indices_bbox_mass_cpp
List split_indices_bbox_mass_cpp(const IntegerVector& idx_parent, const IntegerVector& child_id, const int m, const IntegerVector& x, const IntegerVector& y, const IntegerVector& z, const NumericVector& pi_vec);
RcppExport SEXP _neurothresh_split_indices_bbox_mass_cpp(SEXP idx_parentSEXP, SEXP child_idSEXP, SEXP mSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP pi_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type idx_parent(idx_parentSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type child_id(child_idSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pi_vec(pi_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(split_indices_bbox_mass_cpp(idx_parent, child_id, m, x, y, z, pi_vec));
    return rcpp_result_gen;
END_RCPP
}
// exp_smooth3d_cpp
NumericVector exp_smooth3d_cpp(const NumericVector& vol, const IntegerVector& dims, const NumericVector& lambda_xyz, const int radius_mult);
RcppExport SEXP _neurothresh_exp_smooth3d_cpp(SEXP volSEXP, SEXP dimsSEXP, SEXP lambda_xyzSEXP, SEXP radius_multSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type vol(volSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lambda_xyz(lambda_xyzSEXP);
    Rcpp::traits::input_parameter< const int >::type radius_mult(radius_multSEXP);
    rcpp_result_gen = Rcpp::wrap(exp_smooth3d_cpp(vol, dims, lambda_xyz, radius_mult));
    return rcpp_result_gen;
END_RCPP
}
// octree_split_info_cpp
List octree_split_info_cpp(const IntegerVector& idx_parent, const IntegerVector& bbox, const IntegerVector& x, const IntegerVector& y, const IntegerVector& z, const NumericVector& pi_vec, const double min_pi_mass);
RcppExport SEXP _neurothresh_octree_split_info_cpp(SEXP idx_parentSEXP, SEXP bboxSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP pi_vecSEXP, SEXP min_pi_massSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type idx_parent(idx_parentSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pi_vec(pi_vecSEXP);
    Rcpp::traits::input_parameter< const double >::type min_pi_mass(min_pi_massSEXP);
    rcpp_result_gen = Rcpp::wrap(octree_split_info_cpp(idx_parent, bbox, x, y, z, pi_vec, min_pi_mass));
    return rcpp_result_gen;
END_RCPP
}
// score_children_onepass_cpp
NumericVector score_children_onepass_cpp(const NumericVector& Z_vec, const IntegerVector& idx_parent, const NumericVector& w_parent, const IntegerVector& child_id, const NumericVector& log_den1, const NumericVector& inv_sqrt_den2, const NumericVector& kappa_grid_pos, const bool do_abs);
RcppExport SEXP _neurothresh_score_children_onepass_cpp(SEXP Z_vecSEXP, SEXP idx_parentSEXP, SEXP w_parentSEXP, SEXP child_idSEXP, SEXP log_den1SEXP, SEXP inv_sqrt_den2SEXP, SEXP kappa_grid_posSEXP, SEXP do_absSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type Z_vec(Z_vecSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type idx_parent(idx_parentSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type w_parent(w_parentSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type child_id(child_idSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type log_den1(log_den1SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type inv_sqrt_den2(inv_sqrt_den2SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type kappa_grid_pos(kappa_grid_posSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_abs(do_absSEXP);
    rcpp_result_gen = Rcpp::wrap(score_children_onepass_cpp(Z_vec, idx_parent, w_parent, child_id, log_den1, inv_sqrt_den2, kappa_grid_pos, do_abs));
    return rcpp_result_gen;
END_RCPP
}
// split_indices_cpp
List split_indices_cpp(const IntegerVector& idx_parent, const IntegerVector& child_id, const int m);
RcppExport SEXP _neurothresh_split_indices_cpp(SEXP idx_parentSEXP, SEXP child_idSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type idx_parent(idx_parentSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type child_id(child_idSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(split_indices_cpp(idx_parent, child_id, m));
    return rcpp_result_gen;
END_RCPP
}
// build_den_pyramid_xptr_cpp
SEXP build_den_pyramid_xptr_cpp(const IntegerVector& x0, const IntegerVector& y0, const IntegerVector& z0, const NumericVector& pi_vec, const int side);
RcppExport SEXP _neurothresh_build_den_pyramid_xptr_cpp(SEXP x0SEXP, SEXP y0SEXP, SEXP z0SEXP, SEXP pi_vecSEXP, SEXP sideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pi_vec(pi_vecSEXP);
    Rcpp::traits::input_parameter< const int >::type side(sideSEXP);
    rcpp_result_gen = Rcpp::wrap(build_den_pyramid_xptr_cpp(x0, y0, z0, pi_vec, side));
    return rcpp_result_gen;
END_RCPP
}
// pyramid_max_u0_cpp
double pyramid_max_u0_cpp(const NumericVector& Z_vec, const NumericVector& pi_vec, const IntegerVector& x0, const IntegerVector& y0, const IntegerVector& z0, SEXP den_xptr, const bool do_abs);
RcppExport SEXP _neurothresh_pyramid_max_u0_cpp(SEXP Z_vecSEXP, SEXP pi_vecSEXP, SEXP x0SEXP, SEXP y0SEXP, SEXP z0SEXP, SEXP den_xptrSEXP, SEXP do_absSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type Z_vec(Z_vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pi_vec(pi_vecSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type den_xptr(den_xptrSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_abs(do_absSEXP);
    rcpp_result_gen = Rcpp::wrap(pyramid_max_u0_cpp(Z_vec, pi_vec, x0, y0, z0, den_xptr, do_abs));
    return rcpp_result_gen;
END_RCPP
}
// pyramid_max_u0_signflip_cpp
double pyramid_max_u0_signflip_cpp(const NumericVector& Z_vec, const NumericVector& pi_vec, const IntegerVector& x0, const IntegerVector& y0, const IntegerVector& z0, SEXP den_xptr, const bool do_abs);
RcppExport SEXP _neurothresh_pyramid_max_u0_signflip_cpp(SEXP Z_vecSEXP, SEXP pi_vecSEXP, SEXP x0SEXP, SEXP y0SEXP, SEXP z0SEXP, SEXP den_xptrSEXP, SEXP do_absSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type Z_vec(Z_vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pi_vec(pi_vecSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type den_xptr(den_xptrSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_abs(do_absSEXP);
    rcpp_result_gen = Rcpp::wrap(pyramid_max_u0_signflip_cpp(Z_vec, pi_vec, x0, y0, z0, den_xptr, do_abs));
    return rcpp_result_gen;
END_RCPP
}
// pyramid_scores_u0_cpp
List pyramid_scores_u0_cpp(const NumericVector& Z_vec, const NumericVector& pi_vec, const IntegerVector& x0, const IntegerVector& y0, const IntegerVector& z0, SEXP den_xptr, const bool do_abs);
RcppExport SEXP _neurothresh_pyramid_scores_u0_cpp(SEXP Z_vecSEXP, SEXP pi_vecSEXP, SEXP x0SEXP, SEXP y0SEXP, SEXP z0SEXP, SEXP den_xptrSEXP, SEXP do_absSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type Z_vec(Z_vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pi_vec(pi_vecSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type den_xptr(den_xptrSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_abs(do_absSEXP);
    rcpp_result_gen = Rcpp::wrap(pyramid_scores_u0_cpp(Z_vec, pi_vec, x0, y0, z0, den_xptr, do_abs));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_smooth3d_cpp
NumericVector gaussian_smooth3d_cpp(const NumericVector& vol, const IntegerVector& dims, const NumericVector& sigma_xyz, const int radius_mult);
RcppExport SEXP _neurothresh_gaussian_smooth3d_cpp(SEXP volSEXP, SEXP dimsSEXP, SEXP sigma_xyzSEXP, SEXP radius_multSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type vol(volSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sigma_xyz(sigma_xyzSEXP);
    Rcpp::traits::input_parameter< const int >::type radius_mult(radius_multSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_smooth3d_cpp(vol, dims, sigma_xyz, radius_mult));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_neurothresh_acf_sign_lag_mean_cpp", (DL_FUNC) &_neurothresh_acf_sign_lag_mean_cpp, 5},
    {"_neurothresh_bbox_from_indices_cpp", (DL_FUNC) &_neurothresh_bbox_from_indices_cpp, 4},
    {"_neurothresh_split_indices_bbox_cpp", (DL_FUNC) &_neurothresh_split_indices_bbox_cpp, 6},
    {"_neurothresh_split_indices_bbox_mass_cpp", (DL_FUNC) &_neurothresh_split_indices_bbox_mass_cpp, 7},
    {"_neurothresh_exp_smooth3d_cpp", (DL_FUNC) &_neurothresh_exp_smooth3d_cpp, 4},
    {"_neurothresh_octree_split_info_cpp", (DL_FUNC) &_neurothresh_octree_split_info_cpp, 7},
    {"_neurothresh_score_children_onepass_cpp", (DL_FUNC) &_neurothresh_score_children_onepass_cpp, 8},
    {"_neurothresh_split_indices_cpp", (DL_FUNC) &_neurothresh_split_indices_cpp, 3},
    {"_neurothresh_build_den_pyramid_xptr_cpp", (DL_FUNC) &_neurothresh_build_den_pyramid_xptr_cpp, 5},
    {"_neurothresh_pyramid_max_u0_cpp", (DL_FUNC) &_neurothresh_pyramid_max_u0_cpp, 7},
    {"_neurothresh_pyramid_max_u0_signflip_cpp", (DL_FUNC) &_neurothresh_pyramid_max_u0_signflip_cpp, 7},
    {"_neurothresh_pyramid_scores_u0_cpp", (DL_FUNC) &_neurothresh_pyramid_scores_u0_cpp, 7},
    {"_neurothresh_gaussian_smooth3d_cpp", (DL_FUNC) &_neurothresh_gaussian_smooth3d_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_neurothresh(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
