# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

acf_sign_lag_mean_cpp <- function(z_full, mask_full, dims, lag_xyz, clip = 3.0) {
    .Call(`_neurothresh_acf_sign_lag_mean_cpp`, z_full, mask_full, dims, lag_xyz, clip)
}

bbox_from_indices_cpp <- function(idx, x, y, z) {
    .Call(`_neurothresh_bbox_from_indices_cpp`, idx, x, y, z)
}

split_indices_bbox_cpp <- function(idx_parent, child_id, m, x, y, z) {
    .Call(`_neurothresh_split_indices_bbox_cpp`, idx_parent, child_id, m, x, y, z)
}

split_indices_bbox_mass_cpp <- function(idx_parent, child_id, m, x, y, z, pi_vec) {
    .Call(`_neurothresh_split_indices_bbox_mass_cpp`, idx_parent, child_id, m, x, y, z, pi_vec)
}

exp_smooth3d_cpp <- function(vol, dims, lambda_xyz, radius_mult = 6L) {
    .Call(`_neurothresh_exp_smooth3d_cpp`, vol, dims, lambda_xyz, radius_mult)
}

octree_split_info_cpp <- function(idx_parent, bbox, x, y, z, pi_vec, min_pi_mass = 1e-10) {
    .Call(`_neurothresh_octree_split_info_cpp`, idx_parent, bbox, x, y, z, pi_vec, min_pi_mass)
}

score_children_onepass_cpp <- function(Z_vec, idx_parent, w_parent, child_id, log_den1, inv_sqrt_den2, kappa_grid_pos, do_abs = FALSE) {
    .Call(`_neurothresh_score_children_onepass_cpp`, Z_vec, idx_parent, w_parent, child_id, log_den1, inv_sqrt_den2, kappa_grid_pos, do_abs)
}

split_indices_cpp <- function(idx_parent, child_id, m) {
    .Call(`_neurothresh_split_indices_cpp`, idx_parent, child_id, m)
}

build_den_pyramid_xptr_cpp <- function(x0, y0, z0, pi_vec, side) {
    .Call(`_neurothresh_build_den_pyramid_xptr_cpp`, x0, y0, z0, pi_vec, side)
}

pyramid_max_u0_cpp <- function(Z_vec, pi_vec, x0, y0, z0, den_xptr, do_abs = FALSE) {
    .Call(`_neurothresh_pyramid_max_u0_cpp`, Z_vec, pi_vec, x0, y0, z0, den_xptr, do_abs)
}

pyramid_max_u0_signflip_cpp <- function(Z_vec, pi_vec, x0, y0, z0, den_xptr, do_abs = FALSE) {
    .Call(`_neurothresh_pyramid_max_u0_signflip_cpp`, Z_vec, pi_vec, x0, y0, z0, den_xptr, do_abs)
}

pyramid_scores_u0_cpp <- function(Z_vec, pi_vec, x0, y0, z0, den_xptr, do_abs = FALSE) {
    .Call(`_neurothresh_pyramid_scores_u0_cpp`, Z_vec, pi_vec, x0, y0, z0, den_xptr, do_abs)
}

gaussian_smooth3d_cpp <- function(vol, dims, sigma_xyz, radius_mult = 3L) {
    .Call(`_neurothresh_gaussian_smooth3d_cpp`, vol, dims, sigma_xyz, radius_mult)
}

